FROM registry.ci.openshift.org/ocp/builder:rhel-9-base-nodejs-openshift-4.22 AS build
ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0

# Copy app source
COPY . /opt/app-root/src/app
WORKDIR /opt/app-root/src/app

USER 0

RUN CYPRESS_INSTALL_BINARY=0 \
    node ./.yarn/releases/yarn-4.13.0.cjs install --immutable && \
    node ./.yarn/releases/yarn-4.13.0.cjs build

# Web server container
FROM registry.ci.openshift.org/ocp/4.22:base-rhel9

RUN INSTALL_PKGS="nginx" && \
    dnf install -y --setopt=tsflags=nodocs $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    dnf -y clean all --enablerepo='*' && rm -rf /var/cache/dnf/* && \
    chown -R 1001:0 /var/lib/nginx /var/log/nginx /run && \
    chmod -R ug+rwX /var/lib/nginx /var/log/nginx /run

USER 1001

COPY --from=build /opt/app-root/src/app/dist /opt/app-root/src

CMD nginx -g "daemon off;"